package com.hey.mietunoff.mietunofficial.greendao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "LESSON_MODEL".
 */
@Entity
public class LessonModel implements java.io.Serializable {
    private Integer week;
    private Integer day;
    private String room;
    private String time;
    private String timeFrom;
    private String timeTo;

    @NotNull
    private String groupName;

    @Generated
    public LessonModel() {
    }

    @Generated
    public LessonModel(Integer week, Integer day, String room, String time, String timeFrom, String timeTo, String groupName) {
        this.week = week;
        this.day = day;
        this.room = room;
        this.time = time;
        this.timeFrom = timeFrom;
        this.timeTo = timeTo;
        this.groupName = groupName;
    }

    public Integer getWeek() {
        return week;
    }

    public void setWeek(Integer week) {
        this.week = week;
    }

    public Integer getDay() {
        return day;
    }

    public void setDay(Integer day) {
        this.day = day;
    }

    public String getRoom() {
        return room;
    }

    public void setRoom(String room) {
        this.room = room;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    public String getTimeFrom() {
        return timeFrom;
    }

    public void setTimeFrom(String timeFrom) {
        this.timeFrom = timeFrom;
    }

    public String getTimeTo() {
        return timeTo;
    }

    public void setTimeTo(String timeTo) {
        this.timeTo = timeTo;
    }

    @NotNull
    public String getGroupName() {
        return groupName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setGroupName(@NotNull String groupName) {
        this.groupName = groupName;
    }

}
