package com.hey.mietunoff.mietunofficial;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.NotNull;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "LESSON_MODEL".
 */
@Entity
public class LessonModel {

    @Id(autoincrement = true)
    private Long id;
    private Integer week;
    private Integer day;
    private String room;
    private Integer time;
    private String timeFull;
    private String timeFrom;
    private String timeTo;
    private String teacher;
    private String teacherFull;
    private String disciplineName;
    private String disciplineType;
    private String code;

    @NotNull
    private String groupName;

    @Generated
    public LessonModel() {
    }

    public LessonModel(Long id) {
        this.id = id;
    }

    @Generated
    public LessonModel(Long id, Integer week, Integer day, String room, Integer time, String timeFull, String timeFrom, String timeTo, String teacher, String teacherFull, String disciplineName, String disciplineType, String code, String groupName) {
        this.id = id;
        this.week = week;
        this.day = day;
        this.room = room;
        this.time = time;
        this.timeFull = timeFull;
        this.timeFrom = timeFrom;
        this.timeTo = timeTo;
        this.teacher = teacher;
        this.teacherFull = teacherFull;
        this.disciplineName = disciplineName;
        this.disciplineType = disciplineType;
        this.code = code;
        this.groupName = groupName;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getWeek() {
        return week;
    }

    public void setWeek(Integer week) {
        this.week = week;
    }

    public Integer getDay() {
        return day;
    }

    public void setDay(Integer day) {
        this.day = day;
    }

    public String getRoom() {
        return room;
    }

    public void setRoom(String room) {
        this.room = room;
    }

    public Integer getTime() {
        return time;
    }

    public void setTime(Integer time) {
        this.time = time;
    }

    public String getTimeFull() {
        return timeFull;
    }

    public void setTimeFull(String timeFull) {
        this.timeFull = timeFull;
    }

    public String getTimeFrom() {
        return timeFrom;
    }

    public void setTimeFrom(String timeFrom) {
        this.timeFrom = timeFrom;
    }

    public String getTimeTo() {
        return timeTo;
    }

    public void setTimeTo(String timeTo) {
        this.timeTo = timeTo;
    }

    public String getTeacher() {
        return teacher;
    }

    public void setTeacher(String teacher) {
        this.teacher = teacher;
    }

    public String getTeacherFull() {
        return teacherFull;
    }

    public void setTeacherFull(String teacherFull) {
        this.teacherFull = teacherFull;
    }

    public String getDisciplineName() {
        return disciplineName;
    }

    public void setDisciplineName(String disciplineName) {
        this.disciplineName = disciplineName;
    }

    public String getDisciplineType() {
        return disciplineType;
    }

    public void setDisciplineType(String disciplineType) {
        this.disciplineType = disciplineType;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    @NotNull
    public String getGroupName() {
        return groupName;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setGroupName(@NotNull String groupName) {
        this.groupName = groupName;
    }

}
